Notifier/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from NFBasic import views

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Notifier.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', views.index, name='index'),

    url(r'^login/$', views.user_login, name='user_login'),
    url(r'^logout/$', views.user_logout, name='user_logout'),

    url(r'^view/(?:(\d+)/)?$', views.view, name='view'),
    url(r'^archive/(\d{4}-\d{2})/(?:(\d+)/)?$', views.get_archive, name='archive'),
    url(r'^grade/(\w+?)/(?:(\d+)/)?$', views.get_grade, name='grade'),
    url(r'^detail/(\d+)/$', views.detail, name='detail'),
    url(r'^notify/$', views.notify, name='notify'),
    url(r'^edit/(\d+)/$', views.edit, name='edit'),

)

NFBasic/models.py
from django.db import models
from django.contrib.auth.models import User


class Grade(models.Model):
    grade = models.CharField(max_length=20)

    def __unicode__(self):
        return self.grade


class NotificationMonth(models.Model):
    month = models.DateTimeField()

    def __unicode__(self):
        return self.month.strftime("%Y-%m")


class NotificationImage(models.Model):
    image = models.ImageField(upload_to='images/%Y/%m/%d')
    length = models.CharField(max_length=20)
    md5 = models.CharField(max_length=40)
    view_thumb = models.ImageField(upload_to='images/%Y/%m/%d')
    admin_thumb = models.ImageField(upload_to='images/%Y/%m/%d')

    def __unicode__(self):
        return self.image.name


class NotificationFile(models.Model):
    file = models.FileField(upload_to='files/%Y/%m/%d')
    length = models.CharField(max_length=20)
    md5 = models.CharField(max_length=40)
    image = models.OneToOneField(NotificationImage, blank=True, null=True)

    def __unicode__(self):
        return self.file.name


class Notification(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    user = models.ForeignKey(User)
    created_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)
    grade = models.ForeignKey(Grade)
    month = models.ForeignKey(NotificationMonth)
    images = models.ManyToManyField(NotificationImage, blank=True, null=True)
    files = models.ManyToManyField(NotificationFile, blank=True, null=True)

    def __unicode__(self):
        return self.title

    def show_image(self):
        if self.image:
            return '<a href="%s"><img src="%s" /></a>' % (self.image.url, self.image.url)
        else:
            return 'No Images'
    show_image.allow_tags = True

    def show_admin_thumb(self):
        images = []
        for image in self.images.all():
            images.append('<a href="%s"><img src="%s" /></a>' % (image.admin_thumb.url, image.admin_thumb.url))
        if images:
            return images
        else:
            return 'No images'
    show_admin_thumb.allow_tags = True

NFBasic/forms.py
from django import forms


class NotificationForm(forms.Form):
    choices = (('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('All', 'All'))
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), max_length=50, label='Title')
    content = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '8'}), label='Content')
    grade = forms.ChoiceField(choices=choices, widget=forms.Select(attrs={'class': 'form-control'}), label='Grade')
    delete = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput())


class FileForm(forms.Form):
    file = forms.FileField(widget=forms.FileInput(attrs={'class': 'form-control'}),
                           help_text='not required', label='File')


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(), max_length=30, label='Username')
    password = forms.CharField(widget=forms.PasswordInput(), max_length=30, label='Password')

NFBasic/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib.auth import authenticate, login, logout
from django.views.decorators.csrf import csrf_exempt
from django.core.exceptions import ObjectDoesNotExist
from django.core.files import File
from NFBasic.forms import *
from NFBasic.models import *
from datetime import datetime
from PIL import Image
import imghdr
import hashlib
import re


def index(request):
    recent_list = Notification.objects.all().order_by('modified_time').reverse()[:10]
    context = {'user': request.user.username, 'recent_list': recent_list, 'archive_dict_list': get_archive_dict_list(),
               'grade_dict_list': get_grade_dict_list()}
    return render_to_response('index.html', context)


def detail(request, pid):
    notification = get_object_or_404(Notification, pk=pid)
    nf_list = list(Notification.objects.order_by('created_time').reverse())
    nf_index = nf_list.index(notification)
    if nf_index > 0:
        next_notification = nf_list[nf_index - 1]
    else:
        next_notification = None
    if nf_index < len(nf_list) - 1:
        last_notification = nf_list[nf_index + 1]
    else:
        last_notification = None
    context = {'user': request.user.username, 'notification': notification, 'next': next_notification,
               'last': last_notification, 'archive_dict_list': get_archive_dict_list(),
               'grade_dict_list': get_grade_dict_list()}
    return render_to_response('detail.html', context)


def view(request, page=''):
    nf_list = list(Notification.objects.all().order_by('modified_time').reverse())
    return pageinate(request, nf_list, page)


def get_archive(request, time, page=''):
    archive_time = datetime(int(time[:4]), int(time[5:]), 1)
    archive_month = get_object_or_404(NotificationMonth, month=archive_time)
    nf_list = list(archive_month.notification_set.all().order_by('modified_time').reverse())
    if not nf_list:
        return Http404
    archive_month = archive_month.month.strftime('%Y-%m')
    return pageinate(request, nf_list, page, archive_month)


def get_archive_dict_list():
    archive_list = list(NotificationMonth.objects.all().order_by('month').reverse())
    archive_dict_list = []
    for month in archive_list:
        archive_dict_list.append({'month': month.month.strftime('%Y-%m'), 'num': month.notification_set.count()})
    return archive_dict_list


def get_grade(request, grade, page=''):
    grade = get_object_or_404(Grade, grade=grade)
    nf_list = list(grade.notification_set.all())
    if not nf_list:
        return Http404
    return pageinate(request, nf_list, page, grade=grade)


def get_grade_dict_list():
    grade_list = list(Grade.objects.all())
    grade_dict_list = []
    for grade in grade_list:
        if grade.notification_set.count():
            grade_dict_list.append({'grade': grade.grade, 'num': grade.notification_set.count()})
    return grade_dict_list


def pageinate(request, nf_list, page, archive_month=None, grade=None):
    try:
        page = int(page)
    except TypeError:
        page = 1
    pages = int((len(nf_list) + 10 - 1) / 10)
    if page > pages or page < 1:
        return HttpResponseRedirect('/views/')
    context = {'nf_list': nf_list, 'pages': pages, 'user': request.user.username,
               'archive_dict_list': get_archive_dict_list(), 'archive_month': archive_month,
               'grade_dict_list': get_grade_dict_list(), 'grade': grade}
    if pages > 1:
        context['nf_list'] = nf_list[(page-1)*10: page*10]
        context['page'] = page
        context['last_page'] = page - 1
        context['next_page'] = page + 1
        context['range'] = range(1, pages + 1)
    return render_to_response('notifications.html', context)


@csrf_exempt
def notify(request):
    if not request.user.is_authenticated():
        message = 'Permission Denied! Please login'
        return render_to_response('redirect.html', {'message': message})
    if request.method == 'POST':
        nf_form = NotificationForm(request.POST)
        file_form = FileForm(request.POST, request.FILES)
        if nf_form.is_valid():
            nf_data = nf_form.cleaned_data
            title = nf_data['title']
            content = nf_data['content']
            grade = Grade.objects.filter(grade=nf_data['grade'])
            if not grade:
                grade = Grade.objects.create(grade=nf_data['grade'])
            else:
                grade = grade[0]
            created_time = datetime.now()
            created_time = datetime(created_time.year, created_time.month, 1)
            nf_month = NotificationMonth.objects.filter(month__exact=created_time)
            if not nf_month:
                month = NotificationMonth.objects.create(month=created_time)
            else:
                month = nf_month[0]
            user = request.user
            notification = Notification.objects.create(title=title, content=content, user=user, grade=grade,
                                                       month=month)
            if file_form.is_valid():
                upload_file = NotificationFile.objects.create(file=request.FILES['file'])
                length = len(upload_file.file)
                md5 = hashlib.md5()
                with open(upload_file.file.path, mode='rb') as rb_file:
                    md5.update(rb_file.read())
                    md5_digest = md5.hexdigest()
                same_file = False
                for item in NotificationFile.objects.all():
                    if str(length) == item.length and md5_digest == item.md5:
                        same_file = True
                        upload_file.file.delete(save=False)
                        upload_file.delete()
                        upload_file = item
                        break
                if same_file:
                    if upload_file.image:
                        notification.images.add(upload_file.image)
                    else:
                        notification.files.add(upload_file)
                    notification.save()
                else:
                    upload_file.length = length
                    upload_file.md5 = md5_digest
                    image_type = imghdr.what(upload_file.file.path)
                    upload_file.save()
                    if image_type:
                        upload_image = NotificationImage.objects.create(image=upload_file.file,
                                                                        length=upload_file.length, md5=upload_file.md5)
                        upload_file.image = upload_image
                        upload_file.save()
                        resize_image(upload_image, upload_image.image.path)
                        notification.images.add(upload_image)
                    else:
                        notification.files.add(upload_file)
                    notification.save()
            return HttpResponseRedirect('/Notifier/detail/%s/' % notification.pk)
        else:
            return HttpResponse('not valid!')
    else:
        nf_form = NotificationForm()
        file_form = FileForm()
        context = {'nf_form': nf_form, 'file_form': file_form, 'user': request.user.username}
        return render_to_response('notify.html', context)


def get_resize_image(image_path, width_limit, height_limit, sub_name):
    image = Image.open(image_path)
    width = image.size[0]
    height = image.size[1]
    if width > width_limit:
        new_width = width_limit
        new_height = new_width * (float(height) / float(width))
    else:
        new_width = width
        new_height = height
    if new_height > height_limit:
        new_height = height_limit
        new_width = new_height * (float(width) / float(height))
    extension = re.search(r'(.\w+)$', image_path).group(1)
    image.thumbnail((new_width, new_height), Image.ANTIALIAS)
    image_path = image_path.replace(extension, sub_name + extension)
    image.save(image_path)
    return image, image_path


def resize_image(image, image_path):
    VIEW_THUMB_WIDTH_LIMIT = 640
    VIEW_THUMB_HEIGHT_LIMIT = 500
    ADMIN_THUMB_WIDTH_LIMIT = 50
    ADMIN_THUMB_HEIGHT_LIMIT = 50
    VIEW_THUMB_NAME = '.view_thumb'
    ADMIN_THUMB_NAME = '.admin_thumb'
    image_file, path = get_resize_image(image_path, VIEW_THUMB_WIDTH_LIMIT, VIEW_THUMB_HEIGHT_LIMIT, VIEW_THUMB_NAME)
    with open(path, 'r') as f:
        image.view_thumb = File(f)
    image_file, path = get_resize_image(image_path, ADMIN_THUMB_WIDTH_LIMIT, ADMIN_THUMB_HEIGHT_LIMIT, ADMIN_THUMB_NAME)
    with open(path, 'r') as f:
        image.admin_thumb = File(f)
    image.save()


@csrf_exempt
def edit(request, pid):
    if not request.user.is_authenticated():
        message = 'Permission Denied! Please login'
        return render_to_response('redirect.html', {'message': message})
    notification = get_object_or_404(Notification, pk=pid)
    if request.method == 'POST':
        nf_form = NotificationForm(request.POST)
        file_form = FileForm(request.POST, request.FILES)
        if nf_form['delete']:
            notification.delete()
            return HttpResponseRedirect('/Notifier/view/')
        if nf_form.is_valid():
            nf_data = nf_form.cleaned_data
            title = nf_data['title']
            content = nf_data['content']
            grade = Grade.objects.filter(grade=nf_data['grade'])
            if not grade:
                grade = Grade.objects.create(grade=nf_data['grade'])
            else:
                grade = grade[0]
            if notification.title != title:
                notification.title = title
            if notification.content != content:
                notification.content = content
            if notification.grade != grade:
                notification.grade = grade
            if file_form.is_valid() and notification.file != request.FILES['file']:

NFBasic/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head lang="en">
  <meta charset="UTF-8">
  <title>Notifier</title>
  <script type="text/javascript" src="{% static 'js/jquery-1.9.1.min.js' %}"></script>
  <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <style type="text/css">
    html {
      position: relative;
      min-height: 100%;
    }
    body {
      padding-top: 70px;
    }
    .footer {
      position: absolute;
      bottom: 0;
      width: 100%;
    }
    .footer hr {
      background-color: #cccccc;
      color: #cccccc;
    }
    .form {
      padding-bottom: 40px;
    }
    .panel-default {
      padding-top: 30px;
      border-color: #ffffff;
    }
    .panel-default > .panel-heading {
      background-color: #ffffff;
      border-bottom-color: #aaaaaa;
    }
    .panel-default > .panel-heading > h3 {
      padding-top: 0;
      line-height: 0;
      color: #428bca;
    }
    .list-group > p, .list-group > a {
      border-color: #ffffff;
    }
    .page-header {
      margin-top: 30px;
      margin-bottom: 10px;
      padding-top: 10px;
      color: #428bca;
      border-bottom-color: #aaaaaa;
    }
    .btn-default {
      border-color: #428bca;
      color: #428bca;
    }
    .modal-footer > .btn-default {
      color: #333333;
      border-color: #cccccc;
    }
  </style>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Notifier for XDU</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li {% block nav_index %} {% endblock %}><a href="{% url 'index' %}">Home</a></li>
        <li {% block nav_notification %} {% endblock %}><a href="{% url 'view' %}">Notification</a></li>
        <li {% block nav_about %} {% endblock %}><a href="#">About</a></li>
        <li {% block nav_contact %} {% endblock %}><a href="#">Contact Us</a></li>
      </ul>
      <div class="navbar-right">
        <div class="navbar-text">
          {% if user %}
            <a href="#">{{ user }}</a>&nbsp;&nbsp;
            <a href="{% url 'user_logout' %}"><span class="glyphicon glyphicon-log-out"></span></a>
          {% else %}
            <a href="{% url 'user_login' %}">login&nbsp;<span class="glyphicon glyphicon-log-in"></span></a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  {% block content %}
    <div class="row">
      <div class="col-md-8">
        {% block recent_nf %}{% endblock %}
        {% block nf_list %}{% endblock %}
        {% block pagination %}{% endblock %}
      </div>

      <div class="col-md-3 col-md-offset-1">
        {% if archive_dict_list %}
          <div class="row">
            <div class="panel panel-default">
              <div class="panel-heading"><h3>Archives</h3></div>
              <div class="list-group">
                {% for item in archive_dict_list|dictsortreversed:"month" %}
                  {% if archive_month == item.month %}
                    <p class="list-group-item active">{{ item.month }}<span class="badge">{{ item.num }}</span></p>
                  {% else %}
                    <a href="{% url 'archive' item.month %}" class="list-group-item">{{ item.month }}
                      <span class="badge">{{ item.num }}</span>
                    </a>
                  {% endif %}
                {% endfor %}
              </div>
            </div>
          </div>
        {% endif %}

        {% if grade_dict_list %}
          <div class="row">
            <div class="panel panel-default">
              <div class="panel-heading"><h3>Grade</h3></div>
              <div class="list-group">
                {% for item in grade_dict_list|dictsortreversed:"grade" %}
                  {% if item.grade == grade.grade %}
                    <p class="list-group-item active">{{ item.grade }}<span class="badge">{{ item.num }}</span> </p>
                  {% else %}
                    <a href="{% url 'grade' item.grade %}" class="list-group-item">{{ item.grade }}
                      <span class="badge">{{ item.num }}</span>
                    </a>
                  {% endif %}
                {% endfor %}
              </div>
            </div>
          </div>
        {% endif %}
      </div>
    </div>
  {% endblock %}
</div><br><br><br><br>

<div class="footer">
  <div class="hr"><hr></div>
  <div class="container">
    <p class="text-center"><a href="#"><span class="glyphicon glyphicon-arrow-up"></span>Back to top</a></p>
    <p class="text-muted text-center">Copyright ©2014 All rights reserved.</p>
  </div>
</div>

{% block script %}{% endblock %}
</body>
</html>

NFBasic/templates/base_notifications.html
{% extends 'base.html' %}

{% block nav_notification %}
  class = 'active'
{% endblock %}

NFBasic/templates/detail.html
{% extends 'base_notifications.html' %}
{% load static %}

{% block nf_list %}
  <div>
    <h2 class="page-header">{{ notification.title }}</h2>

    <div class="row" style="padding-top: 5px;">
      <div class="col-md-9">
        <div class="text-left">
          <a href="{% url 'grade' notification.grade %}" class="btn btn-sm btn-default">{{ notification.grade }}</a>
        </div>
      </div>
      <div class="col-md-3">
        <div class="text-right">
          <p class="text-muted"> {{ notification.created_time|date:"Y-m-j H:i:s" }} </p>
        </div>
      </div>
    </div>

    {{ notification.content|safe|linebreaks }}

    <br>

    {% if notification.file %}
      <img src="{{ notification.file.url }}"/>
    {% endif %}
    <div class="row"><br><br></div>

    <div class="row">
      <div class="pull-right">
        <div class="btn-group">
          <a href="{% url 'view' %}" class="btn btn-primary" role="button"><span class="glyphicon glyphicon-chevron-left"></span> Back</a>
          {% if user %}
            <a href="{% url 'edit' notification.pk %}" class="btn btn-primary" role="button"><span class="glyphicon glyphicon-edit"></span> Edit</a>
          {% endif %}
        </div>
      </div>
    </div><br><br>

    <div class="row">
      {% if last %}
        <a class="pull-left" href="{% url 'detail' last.pk %}"><span class="glyphicon glyphicon-chevron-left"></span> {{ last.title }}</a>
      {% else %}
        <p class="text-muted pull-left"><span class="glyphicon glyphicon-chevron-left"></span> 已是第一篇</p>
      {% endif %}
      {% if next %}
        <a class="pull-right" href="{% url "detail" next.pk %}">{{ next.title }} <span class="glyphicon glyphicon-chevron-right"></span></a>
      {% else %}
        <p class="text-muted pull-right">已是最后一篇 <span class="glyphicon glyphicon-chevron-right"></span></p>
      {% endif %}
    </div>
  </div><br><br>
{% endblock %}

NFBasic/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block nav_index %}
  class = 'active'
{% endblock %}

{% block recent_nf %}

  {% if user %}
    <div class="row">
      <div class="pull-right" style="padding-top: 43px;">
        <a href="{% url 'notify' %}" class="btn btn-primary" role="button"><span class="glyphicon glyphicon-plus"></span> New notification</a>
      </div>
    </div>
  {% endif %}
  <h2>Recent Notification</h2>
  {% for notification in recent_list %}
    <div class="row">
      <div>
        <h2 class="page-header">
          <a href="{% url 'detail' notification.pk %}">
            {{ notification.title }}
          </a>
        </h2>

        <div class="row" style="padding-top: 5px;padding-bottom: 10px">
          <div class="col-md-9">
            <div class="text-left">
              <div class="btn-group">
                <a href="{% url 'grade' notification.grade %}" class="btn btn-sm btn-default">{{ notification.grade }}</a>
                <a class="btn btn-sm btn-default">{{ notification.user }}</a>
              </div>
            </div>
          </div>

          <div class="col-md-3">
            <div class="text-right">
              <p class="text-muted"> {{ notification.created_time|date:"Y-m-j H:i:s" }} </p>
            </div>
          </div>
        </div>

        {{ notification.content|safe|linebreaks|truncatewords_html:150 }}
      </div><br><br>
    </div>
  {% endfor %}
  {% if not recent_list %}
    <h3 class="text-muted">No recent notifications</h3>
  {% endif %}

{% endblock %}

NFBasic/templates/login.html
{% extends 'base.html' %}

{% block content %}
  <form id="login_form" style="padding-top: 30px;" class="form" method="post">
  {% csrf_token %}
    <div class="form-group">
      <label class="control-label" for="id_username">{{ login_form.username.label }}</label>
      {{ login_form.username }}
    </div>
    <div class="form-group">
      <label class="control-label" for="id_password">{{ login_form.password.label }}</label>
      {{ login_form.password }}
    </div>
  <button type="submit" class="btn btn-primary">login</button>
  </form>
{% endblock %}

NFBasic/templates/notifications.html
{% extends 'base_notifications.html' %}

{% block nf_list %}

  {% if user and not archive_month and not grade %}
    <div class="row">
        <div class="pull-right" style="padding-top: 43px;">
          <a href="{% url 'notify' %}" class="btn btn-primary" role="button"><span class="glyphicon glyphicon-plus"></span> New notification</a>
        </div>
    </div>
  {% endif %}

  {% for notification in nf_list %}
    <div class="row">
      <div>
        <h2 class="page-header">
          <a href="{% url 'detail' notification.pk %}">
            {{ notification.title }}
          </a>
        </h2>

        <div class="row" style="padding-top: 5px;padding-bottom: 10px">
          <div class="col-md-9">
            <div class="text-left">
              <a href="{% url 'grade' notification.grade %}" class="btn btn-sm btn-default">{{ notification.grade }}</a>
            </div>
          </div>

          <div class="col-md-3">
            <div class="text-right">
              <p class="text-muted"> {{ notification.created_time|date:"Y-m-j H:i:s" }} </p>
            </div>
          </div>
        </div>

        {{ notification.content|safe|linebreaks|truncatewords_html:150 }}
      </div><br><br>
    </div>
  {% endfor %}

{% endblock %}

{% block pagination %}

  {% if pages > 1 %}
    <div class="row">
      <ul class="pagination pagination-lg pull-left">
        {% if page != 1 %}
          {% if grade %}
            <li><a href="{% url 'grade' grade last_page %}">&laquo;</a></li>
          {% elif archive_month %}
            <li><a href="{% url 'archive' archive_month last_page %}">&laquo;</a></li>
          {% else %}
            <li><a href="{% url 'view' last_page %}">&laquo;</a></li>
          {% endif %}
        {% else %}
          <li class="disabled"><span>&laquo;</span></li>
        {% endif %}

        {% for i in range %}
          {% if i == page %}
            <li class="active"><span>{{ i }}<span class="sr-only">(current)</span></span></li>
          {% else %}
            {% if grade %}
              <li><a href="{% url 'grade' grade i %}">{{ i }}</a></li>
            {% elif archive_month %}
              <li><a href="{% url 'archive' archive_month i %}">{{ i }}</a></li>
            {% else %}
              <li><a href="{% url 'view' i %}">{{ i }}</a></li>
            {% endif %}
          {% endif %}
        {% endfor %}

        {% if page != pages %}
          {% if grade %}
            <li><a href="{% url 'grade' grade next_page %}">&raquo;</a></li>
          {% elif archive_month %}
            <li><a href="{% url 'archive' archive_month next_page %}">&raquo;</a></li>
          {% else %}
            <li><a href="{% url 'view' last_page %}">&raquo;</a></li>
          {% endif %}
        {% else %}
          <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
      </ul>
    </div>
  {% endif %}

{% endblock %}

NFBasic/templates/notify.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <form id="nf_form" class="form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
      <label class="control-label" for="id_title">{{ nf_form.title.label }}</label>
      {{ nf_form.title }}
    </div>
    <div class="form-group">
      <label class="control-label" for="id_content">{{ nf_form.content.label }}</label>
      {{ nf_form.content }}
    </div>
    <div class="form-group">
      <label class="control-label" for="id_grade">{{ nf_form.grade.label }}</label>
      {{ nf_form.grade }}
    </div>
    <div class="form-group">
      <label class="control-label" for="id_file">{{ file_form.file.label }}</label>
      {{ file_form.file }}
      <span class="help-block">{{ file_form.file.help_text }}</span>
    </div>
    <div class="form-group">
      {{ nf_form.delete }}
    </div>
    <div class="btn-group">
      {% if notification %}
        <a class="btn btn-primary" href="{% url 'detail' notification.pk %}"><span class="glyphicon glyphicon-remove"></span> Cancel</a>
      {% else %}
        <a class="btn btn-primary" href="{% url 'view' %}"><span class="glyphicon glyphicon-remove"></span> Cancel</a>
      {% endif %}
      <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-ok"></span> Submit</button>
      {% if edit %}
        <button type="button" class="btn btn-primary" onclick="nf_delete();"><span class="glyphicon glyphicon-trash"></span> Delete</button>
      {% endif %}
    </div>
  </form>
{% endblock %}

{% block script %}
  <script type="text/javascript">
    function nf_delete(){
        var form = document.getElementById('nf_form');
        form.delete.value = true;
        form.submit();
      }
  </script>
{% endblock %}

NFBasic/templates/redirect.html
{% extends 'base.html' %}

{% block content %}
  {% if message %}
    <div class="text-center">
      <h2>{{ message }}</h2>
      <a href="/Notifier/">back to index</a>
    </div>
  {% endif %}
{% endblock %}